---
- include_tasks: initialize_cluster_master.yml

- include_tasks: ../../../roles/splunk_common/tasks/enable_forwarding.yml

- include_tasks: ../../../roles/splunk_common/tasks/provision_apps.yml
  when:
    - splunk.apps_location

- include_tasks: push_apps_to_indexers.yml
  when:
    - splunk.apps_location

- include_tasks: ../../splunk_common/tasks/set_as_hec_receiver.yml
  vars:
    splunk_hec_inputs_app_path: "apps/splunk_httpinput/local"
  when:
    - first_run | bool
    - not splunk.hec_disabled | bool
    - splunk.hec_token is defined and splunk.hec_token != None

- include_tasks: ../../../roles/splunk_common/tasks/disable_installed_apps.yml
  when:
    - splunk.apps_location

- include_tasks: setup_multisite.yml
  when:
    - splunk.site is defined
    - splunk.all_sites is defined
    - splunk.multisite_replication_factor_origin is defined
    - splunk.multisite_replication_factor_total is defined
    - splunk.multisite_search_factor_origin is defined
    - splunk.multisite_search_factor_total is defined


- include_tasks: ../../../roles/splunk_common/tasks/check_for_required_restarts.yml
