---
- name: "Create .ui_login"
  file:
    path: "{{ splunk.home }}/etc/.ui_login"
    state: touch
    owner: "{{ splunk.user }}"
    group: "{{ splunk.group }}"
    mode: "u=rw,g=,o="
  become: yes
  become_user: "{{ splunk.user }}"