---
- name: Enable HEC services
  ini_file:
    path: "{{ splunk_hec_inputs_app_path }}/local/inputs.conf"
    section: http
    option: disabled
    value: 0
    mode: '0600'
    backup: no
  ignore_errors: true
  when: not splunk.hec_disabled|bool
  register: splunk_hec_input
  no_log: "{{ hide_password }}"

- name: Create new HEC token
  ini_file:
    path: "{{ splunk_hec_inputs_app_path} }/local/inputs.conf"
    section: "http://{{ splunk_hec_token }}"
    option: token
    value: "{{ splunk.hec_token }}"
    mode: '0600'
    backup: no
  ignore_errors: true
  when: not splunk.hec_disabled|bool
  register: splunk_hec_input

- name: Enable HEC new-token
  ini_file:
    path: "{{ splunk_hec_inputs_app_path }}/local/inputs.conf"
    section: "http://{{ splunk_hec_token }}"
    option: disabled
    value: "0"
    mode: '0600'
    backup: no
  ignore_errors: true
  when: not splunk.hec_disabled|bool
  register: splunk_hec_input
